[package]
name = "windows-build-tools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wbt"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.6"
