#!/usr/bin/env bash

set -euo pipefail

script_dir=$(dirname $(readlink -f $0))

export RUSTFLAGS="--deny warnings"
export CARGO_TARGET_DIR="$script_dir/target/check"
echo "format code"
cargo fmt
echo "build"
cargo build
echo "run clippy"
cargo clippy
echo "run test"
cargo test
