name: CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check:
    name: check
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust toolchain 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59

      - name: is formatted?
        run: cargo fmt --check

      - name: run check
        run: ./check
